addhl global/ number-lines

set global modelinefmt '%val{bufname} %val{cursor_line}:%val{cursor_char_column} {{context_info}} {{mode_info}} - U+%sh{printf "%04x" "$kak_cursor_char_value"}'

colorscheme tomorrow-night
