(deftheme aldo
  "Created 2017-05-20.")

(custom-theme-set-faces
 'aldo
 '(default ((t (:inherit nil :stipple nil :background "grey99" :foreground "#212121" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 113 :width normal :foundry "PfEd" :family "DejaVu Sans Mono"))))
 '(cursor ((t (:inverse-video t :foreground "#272822" :background "#FF5722"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((t (:foreground "#008ED1"))))
 '(minibuffer-prompt ((t (:weight bold :foreground "#2196f3" :background "gold"))))
 '(highlight ((t (:underline nil :inverse-video nil :background "#ECEFF1"))))
 '(region ((t (:background "#90A4AE" :inherit (highlight)))))
 '(shadow ((t (:foreground "#607d8b" :background "#EEEEEE"))))
 '(secondary-selection ((t (:weight bold :background "#bf616a" :inherit (region)))))
 '(trailing-whitespace ((t (:underline nil :inverse-video t :foreground "#B71C1C" :background "#FFFF57"))))
 '(font-lock-builtin-face ((t (:foreground "#626FC9" :weight normal))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#607d8b"))))
 '(font-lock-comment-face ((t (:foreground "#7f7f7f" :slant italic))))
 '(font-lock-constant-face ((t (:background "#F3F2FF" :foreground "#7653c1"))))
 '(font-lock-doc-face ((t (:foreground "#673ab7"))))
 '(font-lock-function-name-face ((t (:weight normal :foreground "#0097A7"))))
 '(font-lock-keyword-face ((t (:weight normal :foreground "#00796b"))))
 '(font-lock-negation-char-face ((t (:weight bold :foreground "#2196f3"))))
 '(font-lock-preprocessor-face ((t (:foreground "#FFA000"))))
 '(font-lock-regexp-grouping-backslash ((t (:weight bold :foreground "#FFA000" :inherit nil))))
 '(font-lock-regexp-grouping-construct ((t (:weight bold :foreground "#4527A0" :inherit nil))))
 '(font-lock-string-face ((t (:foreground "#689f38" :background "#FDFBF5"))))
 '(font-lock-type-face ((t (:weight normal :slant normal :foreground "#0097A7"))))
 '(font-lock-variable-name-face ((t (:weight normal :foreground "#EF6C00"))))
 '(font-lock-warning-face ((t (:weight bold :slant italic :underline (:color foreground-color :style line) :foreground "#B71C1C"))))
 '(button ((t (:underline (:color foreground-color :style line) :foreground "#006DAF"))))
 '(link ((t (:weight normal :underline (:color foreground-color :style line)))))
 '(link-visited ((t (:weight normal :underline (:color foreground-color :style line) :foreground "#E5786D"))))
 '(fringe ((t (:foreground "#9B9B9B" :background "#ECEFF1"))))
 '(header-line ((t (:weight bold :underline (:color "black" :style line) :overline "black" :box (:line-width 1 :color "#64645E" :style unspecified) :foreground "#4527A0" :inherit (mode-line)))))
 '(tooltip ((t (:foreground "black" :background "light yellow" :inherit (default)))))
 '(mode-line ((t (:background "#e8e8e8" :foreground "black"))))
 '(mode-line-buffer-id ((t (:weight bold :foreground "#212121"))))
 '(mode-line-emphasis ((t (:weight bold :slant italic :foreground "#212121"))))
 '(mode-line-highlight ((t (:box (:line-width 2 :color "9599B0" :style released-button)))))
 '(mode-line-inactive ((t (:weight normal :box (:line-width -1 :color "#a5a5a5" :style nil) :foreground "#a7adba" :background "#ECEFF1" :inherit (mode-line)))))
 '(isearch ((t (:weight bold :underline (:color "#FF9632" :style line) :foreground "#FAFAFA" :background "#558b2f" :inherit (region)))))
 '(isearch-fail ((t (:weight bold :inverse-video t :foreground "black" :background "#FAFAFA" :inherit (font-lock-warning-face)))))
 '(lazy-highlight ((t (:underline (:color "#FF9632" :style line) :inverse-video nil :foreground "#FAFAFA" :background "#558b2f" :inherit (highlight)))))
 '(match ((t (:weight bold :inverse-video nil :foreground "#FAFAFA" :background "#558b2f"))))
 '(next-error ((t (:underline nil :background "#FFF876"))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'aldo)
