# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
[ -f $HOME/dotfiles/bash/functions.sh ] && source $HOME/dotfiles/bash/functions.sh
[ -f $HOME/dotfiles/bash/alias.sh ] && source $HOME/dotfiles/bash/alias.sh

# add binary PATH
[ -d $HOME/.bin ] && pathmunge $HOME/.bin
[ -d $HOME/bin ] && pathmunge $HOME/bin
[ -d $HOME/.local/bin ] && pathmunge $HOME/.local/bin

# flatpak bin
if [ -d /var/lib/flatpak/exports/bin ]; then
    pathmunge /var/lib/flatpak/exports/bin
fi

# Rust bin
if [ -d $HOME/.cargo/bin ]; then
    pathmunge $HOME/.cargo/bin
fi

# Python cache
export PYTHONDONTWRITEBYTECODE=1

# UTF-8
export LANG=en_US.UTF-8

# Prevent execution of wrong command
shopt -s histverify

# Not emacs
if [ ! -v INSIDE_EMACS ]; then
   # Search in history - UP & DOWN arrow
   bind '"\e[A":history-search-backward'
   bind '"\e[B":history-search-forward'
fi

# History
shopt -s histappend
export SAVEHIST=1
export HISTSIZE=100000
export HISTFILE=~/.bash_history

# History to ignore: history command, preceding space char, duplicates
export HISTIGNORE="history*:[ \t]*:&"

shopt -s autocd
shopt -s cmdhist
