# -*- mode: shell-script; -*-
# .bash_profile
# for login shell.
# eg. ssh, login prompt tty1, bash -l
# sourced by GDM

###############
# ENVIRONMENT #
###############

# Python cache
export PYTHONDONTWRITEBYTECODE=1

# Calling bashrc if we are interactive
[[ $- == *i* ]] && [ -t 0 ] \
    && [ -t 1 ] &&  source ~/.bashrc



# Show some art
case $- in
    *i*) center "▶ This shell is interactive ◀ "; show_art ;;
    *) : ;;
esac
