# -*- mode: shell-script; -*-
# .bashrc
# for non-login shell.
# eg. new terminal window, inside screen or tmux

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
bash_dir=$(dirname "$(realpath ~/.bashrc)")

[ -f "$bash_dir/functions.sh" ] && source "$bash_dir/functions.sh"
[ -f '$bash_dir/alias.sh' ] && source "$bash_dir/alias.sh"

unset -v bash_dir

# add binary PATH
[ -d $HOME/.bin ] && pathmunge $HOME/.bin
[ -d $HOME/bin ] && pathmunge $HOME/bin
[ -d $HOME/.local/bin ] && pathmunge $HOME/.local/bin

# flatpak bin
if [ -d /var/lib/flatpak/exports/bin ]; then
    pathmunge /var/lib/flatpak/exports/bin
fi

# Rust bin
if [ -d $HOME/.cargo/bin ]; then
    pathmunge $HOME/.cargo/bin
fi

# Not emacs and interactive
if [ ! -v "INSIDE_EMACS" ] && [ -z "$PS1" ]; then
   # Search in history - UP & DOWN arrow
   bind '"\e[A":history-search-backward'
   bind '"\e[B":history-search-forward'
fi

# AutoCD: change to folder if no command found. Only in version > 4.
[ "${BASH_VERSINFO[0]}" -ge 4 ] && shopt -s autocd

# Multi-line command
shopt -s cmdhist

# Prevent execution of wrong command
shopt -s histverify

# History
shopt -s histappend
export SAVEHIST=10000000
export HISTSIZE=100000
export HISTFILE=~/.bash_history

# History to ignore: history command, preceding space char, duplicates
export HISTIGNORE="history*:[ \t]*:&"

# TODO: Not working yet
export PATH=$(remove_dups_path "$PATH")
