# -*- mode: shell-script; -*-
# .bashrc
# for non-login shell.
# eg. new terminal window, inside screen or tmux

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
BASHRC_DIR=$(dirname "$(realpath ~/.bashrc)")

[ -f "${BASHRC_DIR}/functions.sh" ] && source "${BASHRC_DIR}/functions.sh"
[ -f "${BASHRC_DIR}/alias.sh" ] && source "${BASHRC_DIR}/alias.sh"

unset -v

# add binary PATH
[ -d $HOME/.bin ] && pathmunge $HOME/.bin
[ -d $HOME/bin ] && pathmunge $HOME/bin
[ -d $HOME/.local/bin ] && pathmunge $HOME/.local/bin

# flatpak bin
if [ -d /var/lib/flatpak/exports/bin ]; then
    pathmunge /var/lib/flatpak/exports/bin
fi

# Rust bin
if [ -d $HOME/.cargo/bin ]; then
    pathmunge $HOME/.cargo/bin
fi

# Multi-line command
shopt -s cmdhist

# Prevent execution of wrong command
shopt -s histverify

# History
shopt -s histappend
export SAVEHIST=1000000000
export HISTSIZE=1000000000
export HISTFILESIZE=-1
export HISTFILE=~/.bash_history

# History to ignore: history command, preceding space char, duplicates
export HISTIGNORE="history*:[ \t]*:&"

# Ignore common commands
export HISTIGNORE="$HISTIGNORE:pwd:ls:cd"

# Path remove duplicates
export PATH=$(remove_dups_path "$PATH")
